### PR TITLE
Implement Database.get(id, default=None)

### PR DESCRIPTION
**Pull request by adrienverge**
Provide a helper `Database.get()` to allow trading:

```python
try:
    doc = await db["counter"]
except NotFoundError:
    doc = {"_id": "counter", "value": 1}
```

for:

```python
doc = await db.get("counter", {"value": 1})
```

---

*v1 of the pull request:*

~Provide a helper `Database.get()`, similar to couchdb-python [1], to
allow trading:~

```python
try:
    doc = await db["counter"]
except NotFoundError:
    doc = {"_id": "counter", "value": 1}
```

~for:~

```python
doc = await db.get("counter", {"_id": "counter", "value": 1})
```

~\[1]: https://couchdb-python.readthedocs.io/en/latest/client.html#couchdb.client.Database.get~

### CODE REVIEW

**Comment by bmario** [comment]
The same argument like in #10.

I can see the need for a `db.get()`, I even like the default parameter. In addition, a `create` parameter would be nice, but it should always return a Document object. That you always get a Document object (or Database object respectively) from the interface is a deliberate design choice for me.

What do you think about this instead: https://github.com/metricq/aiocouch/tree/feature-database-get

**Comment by adrienverge** [comment]
> That you always get a Document object (or Database object respectively) from the interface is a deliberate design choice for me.

Agreed, that's a good thing.

> What do you think about this instead: https://github.com/metricq/aiocouch/tree/feature-database-get

I'm loving it! I updated the pull request to use it, but with a modification:
```diff
@@ -116,11 +116,8 @@ class Database(RemoteDatabase):
     async def __getitem__(self, id):
         return await self.get(id)
 
-    async def get(self, id, default=None, create=False):
+    async def get(self, id, default=None):
         doc = Document(self, id)
-        if create and not default:
-            default = {}
-
         try:
             await doc.fetch(discard_changes=True)
         except NotFoundError as e:
```
... because (1) using `default` implies `create=True` and (2) using `create=True` without `default` doesn't really make sense.
Hence, I believe removing `create` makes the API as minimal and future-prood as possible. What do you think?

Other option (I like it less): just keep `create` keyword argument:
```python
    async def get(self, id, create=False):
        doc = Document(self, id)
        if create is not False and not isinstance(create, dict):
            create = {}

        try:
            await doc.fetch(discard_changes=True)
        except NotFoundError as e:
            if create is not None:
                doc.update(create)

```

**Comment by bmario** [comment]
I agree regarding the `create` parameter and adapted my branch. I prefer my branch, because it also provides some tests. Thanks for the idea though.

**Comment by adrienverge** [comment]
No worries. Thanks for taking care of tests!

**Pull request closed without merging**
